version: "3.9"
services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx/php-a.conf:/etc/nginx/conf.d/php-a.conf
            - ../:/var/www/php-a/
    php:
        build: ./php/
        volumes:
            - ../:/var/www/php-a/
